branches:
  only:
    - master

language: python
python:
- '2.7'
- '3.3'

services:
  - postgresql

install: pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: python test.py --cov-report=term --cov-report=html --cov=application/ tests/
