"""Added "outgoing_to" field for messages

Revision ID: 4f9273ae888e
Revises: a0fb193b6085
Create Date: 2017-08-22 12:15:33.831282

"""

# revision identifiers, used by Alembic.
revision = '4f9273ae888e'
down_revision = 'a0fb193b6085'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('outgoing_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['outgoing_to'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'outgoing_to')
    ### end Alembic commands ###
