"""Add "last_msg" field to User model for tracking replies

Revision ID: 8ee732cfaa38
Revises: 4f9273ae888e
Create Date: 2017-08-23 15:04:47.789140

"""

# revision identifiers, used by Alembic.
revision = '8ee732cfaa38'
down_revision = '4f9273ae888e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'user', ['outgoing_to'], ['id'])
    op.add_column('user', sa.Column('last_msg', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'message', ['last_msg'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'last_msg')
    op.drop_constraint(None, 'message', type_='foreignkey')
    ### end Alembic commands ###
