"""Add Message table, user profile fields, and User Tags tables

Revision ID: a0fb193b6085
Revises: 5aae5ada6624
Create Date: 2017-08-18 15:58:03.630888

"""

# revision identifiers, used by Alembic.
revision = 'a0fb193b6085'
down_revision = '5aae5ada6624'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
