"""Add broadcast_to column to track broadcast message history

Revision ID: d2e661b6ac65
Revises: 9ee63d5e3594
Create Date: 2017-08-24 15:44:13.488321

"""

# revision identifiers, used by Alembic.
revision = 'd2e661b6ac65'
down_revision = '9ee63d5e3594'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('broadcast_to', sa.String(length=2048), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'broadcast_to')
    ### end Alembic commands ###
