"""Add user tags database tables

Revision ID: ea9ac38b8a91
Revises: 5b53feda72cd
Create Date: 2017-08-11 16:40:37.719924

"""

# revision identifiers, used by Alembic.
revision = 'ea9ac38b8a91'
down_revision = '5b53feda72cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_type', sa.String(length=255), nullable=True),
    sa.Column('tag_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'name')
    op.drop_table('user_tag')
    op.drop_table('tag')
    ### end Alembic commands ###
